<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>hu.bme.aut</groupId>
	<artifactId>social-community-thread-backend</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>social-community-thread-backend</name>
	<description>Aggregator for all modules</description>

	<modules>
		<module>build/legacy-parent</module>
		<module>build/parent</module>
		<module>libs/events</module>
		<module>libs/common-web</module>
		<module>libs/user-projection</module>
		<module>libs/test-support</module>
		<module>services/auth-service</module>
		<module>gateway</module>
		<module>services/thread-service</module>
		<module>services/friend-service</module>
		<module>common</module>
		<module>chat_service</module>
	</modules>
</project>
