spring.application.name=friend-service
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=qa
spring.cloud.config.profile=qa

eureka.instance.hostname=localhost

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.jpa.generate-ddl=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=0

spring.data.rest.detection-strategy=annotated
